# Python and NumPy Intro

Adapted from the `CS231n` Python tutorial by Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).

## Introduction

Python merupakan bahasa pemrograman yang general yang bisa dipakai untuk banyak hal, tetapi dengan munculnya banyak library terkenal seperti (numpy, scipy, matplotlib) membuat Python menjadi bahasa pemrograman yang sangat bagus untuk digunakan untuk scientific computing.

Kami mengharapkan para peserta sudah memiliki pengalaman sedikit dengan Python dan numpy, bagi kalian yang belum pernah mencoba atau menggunakan Python dan numpy maka pada sesi kali ini kita akan sedikit menilik keduanya agar materi selanjutnya bisa dimengerti.

In this tutorial, we will cover:

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting
* Matplotlib: Plotting, Subplots, Images
* IPython: Creating notebooks, Typical workflows

## Basics of Python

Python merupakan bahasa pemrograman yang high-level dan dynamically typed, Kode dari Python sering hampil dikatakan mirip seperti pseudocode, hal tersebut dikarenakan kode-kode Python sangat bersih dan bisa mengekspresikan sesuatu hanya dengan beberapa baris kode.

### Python versions

Ada 2 versi Python untuk sekarang ini, versi 2 dan versi 3. Versi 3 memiliki banyak backwards-incompatible dengan versi 2. Backwards-incompatible berarti ada kode yang bisa dijalankan pada pada Python 2 tetapi tidak bisa dijalankan pada Python 3 dan sebaliknya.

Kita bisa mengecek versi Python dengan menjalankan perintan `python --version` pada terminal.

### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [7]:
x = 3
print(x)
type(x)

3


int

In [8]:
print(x + 1)   # Addition;
print(x - 1)   # Subtraction;
print(x * 2)   # Multiplication;
print(x ** 2)  # Exponentiation;

4
2
6
9


In [9]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

4
8


In [10]:
y = 2.5
print(type(y)) # Prints "<type 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


Python tidak memiliki unary increment (x++) atau decrement (x--) operator.

Python juga memiliki tipe data built-in untuk long integers dan complex numbers, untuk lebih detail baca dokumentasi berikut. [documentation](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-long-complex).

#### Booleans

Untuk urusan Boolean logic, Python banyak menggunakan kata dari bahasa Inggris dan tidak menggunakan simbol-simbol seperti yang digunakan pada bahasa pemrograman lainnya.
&& => and
|| => or

In [12]:
t, f = True, False
print(type(t)) # Prints "<type 'bool'>"

<class 'bool'>


Mari kita liat Boolean operation:

In [19]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

False
True
False
True


#### Strings

In [16]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print(hello, len(hello))

hello 5


In [17]:
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"

hello world


Objek dari string memiliki banyak method, beberapa yg sering digunakan:

In [18]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                               # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


Untuk lebih lengkapnya bisa dibaca pada dokumentasi berikut [documentation](https://docs.python.org/3/library/stdtypes.html#string-methods).

### Containers

Python memiliki beberapa tipe built-in container seperti lists, dictionaries, sets dan tuples.

#### Lists

Apabila bahasa pemrograman lain memiliki array, maka Python memiliki list, list sama seperti array tetapi list memiliki ukuran yang resizeable dan bisa berisi elemen-elemen dengan tipe yang berbeda.

In [2]:
xs = [3, 1, 9]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

[3, 1, 9] 9
9


In [3]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

[3, 1, 'foo']


In [4]:
xs.append('bar') # Add a new element to the end of the list
print(xs)  

[3, 1, 'foo', 'bar']


In [5]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs) 

bar [3, 1, 'foo']


Untuk lebih detail mengenai lists silahkan baca pada dokumentasi berikut [documentation](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists).

#### Slicing

Slicing bisa digunakan untuk mengakses elemen-elemen yang ada pada lists.

In [9]:
nums = [0, 1, 2, 3, 4]

print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 8, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


#### Loops

Kita bisa melakukan looping pada list seperti ini:

In [10]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


Kita bisa mendapatkan index dari elemen yang kita looping dengan menggunakan fungsi `enumerate`:

In [1]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print(idx + 1, animal)

1 cat
2 dog
3 monkey


#### List comprehensions:

Ketika kita menulis kode kita sering ingin melakukan transformasi tipe data, contoh sederhananya seperti ini:

In [13]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


Kita bisa membuat kode ini lebih sederhana dengan menggunakan list comprehension:

In [14]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


List comprehensions juga bisa memiliki kondisi if:

In [15]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


#### Dictionaries

Sebuah dictionary menyimpan data berupa (key, value), dictionary pada Python mirip seperti `Map` pada Java atau object pada Javascript.

In [3]:
d = {
    'cat': 'kucing', 
    'fish': 'ikan'
}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "kucing"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

kucing
True


In [4]:
d['lion'] = 'singa'    # Set an entry in a dictionary
print(d['lion'])      # Prints "singa"

singa


In [5]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: 'monkey'

In [6]:
del d['fish']        # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

N/A


Lebih lanjut tentang dictionary bisa kalian baca pada dokumentasi berikut [documentation](https://docs.python.org/3/library/stdtypes.html#dict).

Dictionary comprehension mirip seperti list comprehensions:

In [14]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


#### Functions

Fungsi pada Python didefinisikan dengan menggunakan `def` keyword:

In [16]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


Sering kali kita mendefinisikan Python dengan argument-argumen yang optional:

In [19]:
def hello(name, loud=False):
    if loud:
        print('HELLO, ', name.upper())
    else:
        print('Hello, ', name)

hello('Bob')
hello('Fred', loud=True)

Hello,  Bob
HELLO,  FRED


### Classes

In [26]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, ', self.name.upper())
        else:
            print('Hello, ', self.name)

g = Greeter(name='Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello,  Fred
HELLO,  FRED


## Numpy

Numpy merupakan library untuk scientific computing di Python. Numpy memberikan high-performance multidimensional array dengan berbagai method manipulasi array yang bisa digunakan.

Untuk menggunakan Numpy, pertama kita harus mengimport package `numpy`:

In [2]:
import numpy as np

### Arrays

Kita bisa menginisialisasikan numpy array dari Python lists dan bisa mengakses elemen-elemennya dengan menggunakan square brackets:

In [28]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [29]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [30]:
print(b.shape)                   
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy juga menyediakan banyak fungsi untuk membuat array:

In [31]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [32]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[ 1.  1.]]


In [37]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [40]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [41]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[ 0.02247431  0.57358602]
 [ 0.92221433  0.55348632]]


### Array indexing

Numpy menyediakan beberapa cara untuk melakukan indexing dalam array.

Slicing: Mirip seperti Python lists, numpy array juga bisa melakukan slicing. Semenjak array pada numpy bisa memiliki multidimensi, maka kita harus menspesifikasikan slicenya untuk setiap dimensi:

In [42]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


Apabila kita membuat array dari hasil slice sebuah array dan melakukan perubahan pada array yang kita buat, maka data pada array original akan ikut berubah juga:

In [43]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


### Datatypes

Ketika kita membuat array numpy, numpy secara default akan menebak tipe data apa yang akan dipakai merujuk pada 
elemen-elemen kita, tetapi kita juga menspesifikasikan tipe data numpy saat mendeklarasikannya secara bersamaan:

In [44]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


Baca dokumentasi berikut untuk lebih lanjut seputar tipe data numpy [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

In [3]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [4]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [5]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [6]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [7]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


Untuk melakukan perkalian matriks kita bisa menggunakan method `.dot`:

In [8]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [9]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [10]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Untuk menjumlahkan elemen-elemen pada array, kita bisa menggunakan method `sum`:

In [11]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Untuk operasi matematika lebih lanjut yang bisa kita gunakan pada numpy, kita bisa membaca lebih lengkapnya pada dokumentasi berikut [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Selain dari fungsi-fungsi untuk melakukan operasi matematika, kita juga seringkali diperlukan untuk melakukan `reshape` atau memanipulasi elemen-elemen suatu matriks. Salah satu fungsi yang bisa kita gunakan untuk merubah dimensi suatu matriks pada numpy adalah dengan menggunakan method transpose atau `.T`:

In [12]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [13]:
v = np.array([[1,2,3]])
print(v)
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]
